#!/usr/bin/env python3
"""
AI News RSS Fetcher -> Obsidian Vault
Usage: python scripts/fetch_news.py
Install: pip install feedparser python-dateutil
"""

import feedparser
import json
import os
import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path
from dateutil import parser as dateparser

# ── Config ──────────────────────────────────────────────
VAULT_DIR  = Path(__file__).parent.parent / "vault" / "ai-news"
INDEX_FILE = Path(__file__).parent.parent / "docs" / "news_index.json"
MAX_PER_FEED  = 5
MAX_TOTAL     = 50

RSS_FEEDS = [
    {"name": "VentureBeat AI",  "url": "https://venturebeat.com/category/ai/feed/",         "tag": "industry"},
    {"name": "MIT Tech Review", "url": "https://www.technologyreview.com/feed/",             "tag": "research"},
    {"name": "Google AI Blog",  "url": "https://blog.google/technology/ai/rss/",             "tag": "Google"},
    {"name": "OpenAI News",     "url": "https://openai.com/blog/rss.xml",                    "tag": "OpenAI"},
    {"name": "Anthropic",       "url": "https://www.anthropic.com/rss.xml",                  "tag": "Anthropic"},
    {"name": "Hugging Face",    "url": "https://huggingface.co/blog/feed.xml",               "tag": "opensource"},
    {"name": "Qbitai",          "url": "https://www.qbitai.com/feed",                        "tag": "zh-news"},
    {"name": "Jiqizhixin",      "url": "https://jiqizhixin.com/rss",                         "tag": "zh-news"},
]
# ────────────────────────────────────────────────────────


def slugify(text):
    text = re.sub(r'[^\w\s-]', '', text, flags=re.ASCII)
    return text.strip().replace(' ', '_')[:50]


def entry_id(entry):
    raw = entry.get("link", "") or entry.get("title", "")
    return hashlib.md5(raw.encode()).hexdigest()[:8]


def parse_date(entry):
    for key in ("published", "updated"):
        val = entry.get(key)
        if val:
            try:
                return dateparser.parse(val).astimezone(timezone.utc)
            except Exception:
                pass
    return datetime.now(timezone.utc)


def clean_summary(text):
    text = re.sub(r'<[^>]+>', '', text or "")
    text = re.sub(r'\s+', ' ', text).strip()
    return text[:200] + ("..." if len(text) > 200 else "")


def write_note(data, source, tag):
    VAULT_DIR.mkdir(parents=True, exist_ok=True)
    date_str = data["date"].strftime("%Y-%m-%d")
    safe_id  = slugify(data["title"]) or data["id"]
    filename = f"{date_str}_{data['id']}_{safe_id[:40]}.md"
    filepath = VAULT_DIR / filename
    if filepath.exists():
        return
    content = f"""---
title: "{data['title'].replace('"', "'")}"
source: "{source}"
tag: "{tag}"
date: {date_str}
url: "{data['url']}"
---

# {data['title']}

**Source**: {source}  
**Date**: {date_str}  
**Link**: {data['url']}  
**Tag**: #{tag}

## Summary

{data['summary']}

---
*Auto-generated by AI news fetcher*
"""
    filepath.write_text(content, encoding="utf-8")


def fetch_all():
    all_entries = []
    for feed_cfg in RSS_FEEDS:
        print(f"  Fetching {feed_cfg['name']} ...")
        try:
            feed    = feedparser.parse(feed_cfg["url"])
            entries = feed.entries[:MAX_PER_FEED]
        except Exception as e:
            print(f"    Failed: {e}")
            continue
        for entry in entries:
            data = {
                "id":      entry_id(entry),
                "title":   entry.get("title", "(no title)").strip(),
                "url":     entry.get("link", ""),
                "summary": clean_summary(entry.get("summary", entry.get("description", ""))),
                "date":    parse_date(entry),
                "source":  feed_cfg["name"],
                "tag":     feed_cfg["tag"],
            }
            all_entries.append(data)
            write_note(data, feed_cfg["name"], feed_cfg["tag"])
            print(f"    + {data['title'][:60]}")

    all_entries.sort(key=lambda x: x["date"], reverse=True)
    return all_entries[:MAX_TOTAL]


def write_index(entries):
    INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)
    out = []
    for e in entries:
        out.append({
            "id":      e["id"],
            "title":   e["title"],
            "url":     e["url"],
            "summary": e["summary"],
            "date":    e["date"].strftime("%Y-%m-%d"),
            "source":  e["source"],
            "tag":     e["tag"],
        })
    INDEX_FILE.write_text(
        json.dumps({"updated": datetime.now().strftime("%Y-%m-%d %H:%M"),
                    "items": out},
                   ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    print(f"\nIndex written -> {INDEX_FILE}  ({len(out)} items)")


if __name__ == "__main__":
    print("=== AI News Fetcher ===\n")
    entries = fetch_all()
    write_index(entries)
    print("\nDone.")
